/*
  podwozie.h
  do pozwozie.lib
  mjkh 2012.09.25
*/


void cdecl symstart(void);
void cdecl symstop(void);
void cdecl resetuj(void);
void cdecl oska(int nr, int czywgore);
int  cdecl kierun(void);
void cdecl kwlewo(int nrkola);
void cdecl kwprawo(int nrkola);
int  cdecl kskret(int nrkola);
void cdecl usttryb(int nr);
int  cdecl jakitryb(void);
int  cdecl czyjuz(void);
int  cdecl czywgore(void);


/* eof */
