/*       makra definiujace atrybuty tekstu dla textattr() z conio.h        */
/*                     dla Hercules Graphic Card                           */
/*                            MJKH 1990                                    */

#define	INVISIBLE        0        /*  niewidoczny  (black on black)        */
#define NORMAL           7        /*  normalny  (white on black)           */
#define UNDERLIN         1        /*  normalny podkreslony                 */
#define BLINKING       135        /*  normalny migocacy                    */
#define BLINKUNDER     129        /*  normalny migocacy podkreslony        */
#define INVERSE        112        /*  odwrocony  (black on white)          */
#define BLINKINVER     240        /*  odwrocony migocacy                   */
#define HIGHLIGHT       15        /*  rozjasniony                          */
#define UNDERHIGH        9        /*  rozjasniony podkreslony              */
#define BLINKHIGH      255        /*  rozjasniony migocacy                 */
